name: Rust

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Test
      run: ./target/debug/runt runt-cli-tests
